### ISSUE TITLE
How to achieve reported score in http://aclweb.org/anthology/S18-1116  

### ISSUE THREAD

**Issue by churinochi** [gbcolborne/hypernym_discovery#1]
Hi , thank you for your contribution to hypernym discovery.  I run your sorce code on my laboratory pc, and the result was nearly equal to UnSupervised model referred in http://aclweb.org/anthology/S18-1116. 
Could you tell me how to achieve the main score of hybrid model in http://aclweb.org/anthology/S18-1116 ?

**Comment by gbcolborne** [comment]
@churinochi This repo only contains the code for the supervised model. To implement the hybrid model, you would need to find or create an implementation of the pattern-based algorithm, then create the hybrid model as explained in the paper. 

As for the supervised model, if you are not achieving scores similar to those reported in the paper, I would need more information to figure out where things are going wrong:
- What subtask are you testing on?
- Are you using the default hparams.conf file or did you change any of the settings?
- How many lines does the file produced by word2vec contain?
- When you run prep_data.py, how many queries/candidates have no pretrained embedding? This is shown in the output of the script.

**Comment by gbcolborne** [comment]
If you are not achieving scores close to those reported in the paper (for the supervised model), the most likely cause is that you trained the word embeddings on the raw corpus (on single-word terms only), rather than on the pre-processed corpus (in which multi-word terms have been converted to single tokens by replacing spaces with underscores). The instructions in the README were ambiguous in this regard. I have updated the README to clarify this, and am closing this issue.

**Comment by churinochi** [comment]
Oh thank you so much for your quick response. I will try it !

**Comment by churinochi** [comment]
Hi, I did what you answered , and it worked. Thank you.
But, there are still a little problem. I can not achieve the score in the paper, I can just achieve lower score like MRR 0.3232 , MAP 0.1768 ,P@1 0.254 . I just ran the command written in ReadME. 
Do you have any Idea about what I should consider ?

**Comment by gbcolborne** [comment]
Your scores are getting pretty close to those reported in the paper, e.g. a MAP of 0.19 for the supervised system. To do better, try bigger embeddings (I used 200 in the example recipe to save memory, but I used 300 for SemEval) or playing around with other hyperparameters. Combining this system with a simple pattern-based system like we did for SemEval will achieve even better results, as shown in the paper.

**Comment by churinochi** [comment]
Really thank you for your advise , I understand the condition. I will try that!!

**Comment by churinochi** [comment]
Hi, I tried your advice which you give me a while ago. And it worked ! very interesting! thank you !
Now I am trying to reproduce pattern-based model written in your paper to understand more about the project you did. But it is seemingly little bit difficult for me....
if you are ok, could you give me some hint or advise about how to code the pattern-based model ? 

Thank you.

**Comment by gbcolborne** [comment]
There is a pattern-based implementation here: https://github.com/mmichelsonIF/hearst_patterns_python. It's by one of the authors of this paper: https://www.aclweb.org/anthology/P19-1327. If you have any further questions, please contact me by e-mail. If you encounter any problems with my code, please raise a new issue.
