### ISSUE TITLE
High devLoss

### ISSUE THREAD

**Issue by jonathanjordy** [gbcolborne/hypernym_discovery#2]
Hello, I'm Jonathan and I'm an AI ENgineer Intern in a startup. I really interested in your work and I think your work is the best Hypernym Discovery model that I can find. There is not much stuff related to this Hypernym that has better documentation than yours. Thank you for that.

 So, I was trying your code but I got this problem, the devloss seems to decrease until around epoch 40 and it continues to increase until it reaches the patient. The last devLoss is about 8 if I'm not mistaken, and the MAP can't reach more than 0.25. What do you think I missed? And by the way, I think there is some code that never actually executes, like make_train_dev_split.py, and it's not written in your README.md. Is it optional to run it? But I read that your prediction needs the test corpus that generated by the code I said earlier. Thank you so much.

**Comment by gbcolborne** [comment]
Hi Jonathan, 

Thanks for your comments. Indeed, the training dynamics are weird. At first, I would early stop when dev loss would increase, but then I saw that a relatively high dev MAP could be achieved even when the dev loss increases a lot. As far as I can tell, this is related to the fact that the loss is a classification loss (using negative sampling) whereas what we actually care about is ranking all the candidates given a query.

It's quite possible there is some redundant code in there. It's experimental code, and I am not actively maintaining it at the moment. I am experimenting with a new model at the moment.

Feel free to e-mail me if you want to discuss this further.

**Comment by jonathanjordy** [comment]
Thank you for your fast response. I saw the other closed issue and i just realized that the code you shared is only the supervised one. I'm interested in making the hybrid one. Thank you so much.
