### ISSUE TITLE
get_corpus.sh 

### ISSUE THREAD

**Issue by cgf1986** [gbcolborne/hypernym_discovery#4]
Hi thank you very much for sharing this work!. I have the same issue when running get_corpus.sh. Is it still possible to download the corpus from that link?.

**Comment by gbcolborne** [comment]
I answered this [here](https://github.com/gbcolborne/hypernym_discovery/issues/3#issuecomment-1138703678), but will leave this issue open in case I decide to fix it using something like [gdown](https://github.com/wkentaro/gdown).

**Comment by cgf1986** [comment]
Use this link to request authorization to download the pre_tokenized corpus:
https://competitions.codalab.org/competitions/17119#learn_the_details-terms_and_conditions
