### ISSUE TITLE
Error while replicating on Google Colab: No module named 'task9_scorer' 

### ISSUE THREAD

**Issue by 98saurabh98** [gbcolborne/hypernym_discovery#5]
Shows this error while trying to implement your model on Google Colab. What needs to be done? Should I rather try it on PC? 

Traceback (most recent call last):
  File "predict.py", line 6, in <module>
    from Evaluator import Evaluator
  File "/content/hypernym_discovery/Evaluator.py", line 7, in <module>
    from task9_scorer import average_precision
ModuleNotFoundError: No module named 'task9_scorer'

I can see description regarding task9_scorer in README.md but unable to implement it properly, it seems.

'''Evaluate predictions on the test set using scoring script of SemEval-2018 Task 9:

python2.7 path/to/SemEval-Task9/task9-scorer.py path/to/SemEval-Task9/test/gold/<subtask>.<language>.test.gold.txt path/to/output/pred.txt
'''

**Comment by gbcolborne** [comment]
You have to download the external evaluation script into this repo. The script is available here: https://competitions.codalab.org/competitions/17119#learn_the_details-evaluation-details.
